// API Configuration
//export const API_BASE_URL = 'https://localhost:7084'; 
export const API_BASE_URL = 'http://localhost:5274';

export const ENDPOINTS = {
  LOGIN: `${API_BASE_URL}/api/auth/login`,
  REFRESH_TOKEN: `${API_BASE_URL}/api/auth/refresh`,
  REGISTER: `${API_BASE_URL}/api/auth/register`,
  GOOGLE_LOGIN: `${API_BASE_URL}/api/auth/oauth/google`,
  FORGOT_PASSWORD: `${API_BASE_URL}/api/auth/forgot-password`,
  RESET_PASSWORD: `${API_BASE_URL}/api/auth/reset-password`,
  GET_PROFILE: `${API_BASE_URL}/api/users/me`,
  UPDATE_PROFILE: `${API_BASE_URL}/api/users/me/profile`,
  UPDATE_AVATAR: `${API_BASE_URL}/api/users/me/avatar`,
  CHANGE_PASSWORD: `${API_BASE_URL}/api/users/me/security`,
  CV_GET_MY: `${API_BASE_URL}/api/CVFile/MyCV`,
  CV_GET_HISTORY: `${API_BASE_URL}/api/CVFile/history`,
  CV_UPLOAD: `${API_BASE_URL}/api/CVFile/upload`,
  CV_DELETE: (id) => `${API_BASE_URL}/api/CVFile/${id}`,
  CV_PARSE: (id) => `${API_BASE_URL}/api/CVFile/${id}/parse`,
  CV_STATUS: (id) => `${API_BASE_URL}/api/CVFile/${id}/status`,
  CV_PARSED_DATA: (id) => `${API_BASE_URL}/api/CVFile/${id}/parsed-data`,
  CV_CONFIRM: (id) => `${API_BASE_URL}/api/CVFile/${id}/confirm`,
  JD_GET_HISTORY: `${API_BASE_URL}/api/JDFile/history`,
  JD_UPLOAD: `${API_BASE_URL}/api/JDFile/upload`,
  JD_SUBMIT_TEXT: `${API_BASE_URL}/api/JDFile/text`,
  JD_DELETE: (id) => `${API_BASE_URL}/api/JDFile/${id}`,
  JD_PARSE: (id) => `${API_BASE_URL}/api/JDFile/${id}/parse`,
  JD_STATUS: (id) => `${API_BASE_URL}/api/JDFile/${id}/status`,
  JD_PARSED_DATA: (id) => `${API_BASE_URL}/api/JDFile/${id}/parsed-data`,
  JD_CONFIRM: (id) => `${API_BASE_URL}/api/JDFile/${id}/confirm`,
  JD_MATCH_CV: (jdId, cvId) => `${API_BASE_URL}/api/JDFile/${jdId}/match-cv/${cvId}`,
  JD_FASTCHECK_RESULTS: `${API_BASE_URL}/api/JDFile/fastcheck`,
  INTERVIEW_SESSIONS: `${API_BASE_URL}/api/InterviewSession`,
  INTERVIEW_SESSION: (id) => `${API_BASE_URL}/api/InterviewSession/${id}`,
  INTERVIEW_SESSION_START: (id) => `${API_BASE_URL}/api/InterviewSession/${id}/start`,
  INTERVIEW_SESSION_COMPLETE: (id) => `${API_BASE_URL}/api/InterviewSession/${id}/complete`,
  INTERVIEW_CAMPAIGN: (campaignId) => `${API_BASE_URL}/api/InterviewSession/campaign/${campaignId}`,
  INTERVIEW_CAMPAIGN_RESULT: (campaignId) => `${API_BASE_URL}/api/InterviewSession/campaign/${campaignId}/result`,
  INTERVIEW_ACTIVE_CAMPAIGN: `${API_BASE_URL}/api/InterviewSession/active`,
  INTERVIEW_CAMPAIGN_CANCEL: (campaignId) => `${API_BASE_URL}/api/InterviewSession/campaign/${campaignId}/cancel`,
  INTERVIEW_CAMPAIGN_EXPIRE: (campaignId) => `${API_BASE_URL}/api/InterviewSession/campaign/${campaignId}/expire`,
  INTERVIEW_QUOTA: `${API_BASE_URL}/api/InterviewSession/quota`,
  INTERVIEW_CAPABILITIES: `${API_BASE_URL}/api/InterviewSession/capabilities`,
  INTERVIEW_AVAILABLE_TYPES: (jdId) => `${API_BASE_URL}/api/InterviewSession/jd/${jdId}/available-types`,
  TECHNICAL_INTERVIEW_SESSIONS: `${API_BASE_URL}/api/technical-interviews/sessions`,
  TECHNICAL_INTERVIEW_SESSION: (sessionId) => `${API_BASE_URL}/api/technical-interviews/${sessionId}`,
  TECHNICAL_INTERVIEW_START: (sessionId) => `${API_BASE_URL}/api/technical-interviews/${sessionId}/start`,
  TECHNICAL_INTERVIEW_CURRENT_QUESTION: (sessionId) => `${API_BASE_URL}/api/technical-interviews/${sessionId}/current-question`,
  TECHNICAL_INTERVIEW_ANSWERS: (sessionId) => `${API_BASE_URL}/api/technical-interviews/${sessionId}/answers`,
  TECHNICAL_INTERVIEW_COMPLETE: (sessionId) => `${API_BASE_URL}/api/technical-interviews/${sessionId}/complete`,
  TECHNICAL_INTERVIEW_FEEDBACK: (sessionId) => `${API_BASE_URL}/api/technical-interviews/${sessionId}/feedback`,
  TECHNICAL_INTERVIEW_RESULT: (sessionId) => `${API_BASE_URL}/api/technical-interviews/${sessionId}/result`,
  BEHAVIORAL_INTERVIEW_INITIALIZE: (sessionId) => `${API_BASE_URL}/api/interviews/${sessionId}/behaviour/initialize`,
  BEHAVIORAL_INTERVIEW_START: (sessionId) => `${API_BASE_URL}/api/interviews/${sessionId}/behaviour/start`,
  BEHAVIORAL_INTERVIEW_STATE: (sessionId) => `${API_BASE_URL}/api/interviews/${sessionId}/behaviour/state`,
  BEHAVIORAL_INTERVIEW_CURRENT_QUESTION: (sessionId) => `${API_BASE_URL}/api/interviews/${sessionId}/behaviour/current-question`,
  BEHAVIORAL_INTERVIEW_ANSWER: (sessionId, sessionQuestionId) => `${API_BASE_URL}/api/interviews/${sessionId}/behaviour/questions/${sessionQuestionId}/answers`,
  BEHAVIORAL_INTERVIEW_COMPLETE: (sessionId) => `${API_BASE_URL}/api/interviews/${sessionId}/behaviour/complete`,
  BEHAVIORAL_INTERVIEW_FEEDBACK: (sessionId) => `${API_BASE_URL}/api/interviews/${sessionId}/behaviour/feedback`,
  BEHAVIORAL_INTERVIEW_RESULT: (sessionId) => `${API_BASE_URL}/api/interviews/${sessionId}/behaviour/result`,
  QUESTIONS_GET: `${API_BASE_URL}/api/questions`,
  QUESTIONS_GET_BY_ID: (id) => `${API_BASE_URL}/api/questions/${id}`,
  SAVED_QUESTIONS_GET: `${API_BASE_URL}/api/SavedQuestions`,
  SAVED_QUESTIONS_SAVE: (id) => `${API_BASE_URL}/api/SavedQuestions/${id}`,
  SAVED_QUESTIONS_UNSAVE: (id) => `${API_BASE_URL}/api/SavedQuestions/${id}`,
  ADMIN_USERS: `${API_BASE_URL}/api/admin/users`,
  ADMIN_USER_LOCK: (userId) => `${API_BASE_URL}/api/admin/users/${userId}/lock`,
  ADMIN_USER_UNLOCK: (userId) => `${API_BASE_URL}/api/admin/users/${userId}/unlock`,
  ADMIN_USER_ROLE: (userId) => `${API_BASE_URL}/api/admin/users/${userId}/role`,
  ADMIN_QUESTIONS: `${API_BASE_URL}/api/admin/questions`,
  ADMIN_QUESTIONS_FILTERS: `${API_BASE_URL}/api/admin/questions/filters`,
  ADMIN_QUESTIONS_BY_ID: (id) => `${API_BASE_URL}/api/admin/questions/${id}`,
  ADMIN_QUESTIONS_IMPORT: `${API_BASE_URL}/api/admin/questions/import`,
  AUDIO_SPEECH_TO_TEXT: `${API_BASE_URL}/api/Audio/speech-to-text`,
  AUDIO_SPEECH_TO_TEXT_WS: `${API_BASE_URL.replace(/^http/, 'ws')}/api/Audio/stream-stt`,
  AUDIO_TEXT_TO_SPEECH: `${API_BASE_URL}/api/Audio/text-to-speech`,
  PAYMENT_CREATE: `${API_BASE_URL}/api/payment/create`,
  PAYMENT_CHECK: (orderCode) => `${API_BASE_URL}/api/payment/check/${orderCode}`,
  PAYMENT_WEBHOOK: `${API_BASE_URL}/api/payment/webhook`,
  PAYMENT_VERIFY: (orderId) => `${API_BASE_URL}/api/payment/callback?orderId=${orderId}`,
  SUBSCRIPTION_PLANS: `${API_BASE_URL}/api/subscription-plans`,
  MY_SUBSCRIPTION: `${API_BASE_URL}/api/subscription/me`,
  ADMIN_SUBSCRIPTION_PLANS: `${API_BASE_URL}/api/admin/subscription-plans`,
  ADMIN_SUBSCRIPTION_PLAN_BY_ID: (planId) => `${API_BASE_URL}/api/admin/subscription-plans/${planId}`,
  ADMIN_SUBSCRIPTION_PLAN_STATUS: (planId) => `${API_BASE_URL}/api/admin/subscription-plans/${planId}/status`,
  ADMIN_SUBSCRIPTION_PLAN_PRICES: (planId) => `${API_BASE_URL}/api/admin/subscription-plans/${planId}/prices`,
  ADMIN_SUBSCRIPTION_PRICE_BY_ID: (priceId) => `${API_BASE_URL}/api/admin/subscription-plans/prices/${priceId}`,
  ADMIN_SUBSCRIPTION_PRICE_STATUS: (priceId) => `${API_BASE_URL}/api/admin/subscription-plans/prices/${priceId}/status`,
  ADMIN_SUBSCRIPTION_MONITORING: `${API_BASE_URL}/api/admin/subscription-monitoring/summary`,
  CODING_ADMIN_IMPORT: `${API_BASE_URL}/api/coding/admin/import`,
  CODING_GET_QUESTIONS: (sessionId) => `${API_BASE_URL}/api/coding/questions/${sessionId}`,
  CODING_SUBMIT: `${API_BASE_URL}/api/coding/submit`,
  CODING_SUBMISSION_HISTORY: (sessionId, questionId) => `${API_BASE_URL}/api/coding/submissions/${sessionId}/${questionId}`,
  CODING_LANGUAGES: `${API_BASE_URL}/api/coding/languages`,
  ADMIN_GOOGLE_QUOTA: `${API_BASE_URL}/api/google/quota`,
  ADMIN_GOOGLE_DASHBOARD: `${API_BASE_URL}/api/admin/google/dashboard`,
  ADMIN_PAYMENTS: `${API_BASE_URL}/api/admin/payments`,
  ADMIN_PAYMENTS_STATISTICS: `${API_BASE_URL}/api/admin/payments/statistics`,
  ADMIN_PAYMENTS_RECENT: `${API_BASE_URL}/api/admin/payments/recent`,
  ADMIN_PAYMENTS_EXPORT: `${API_BASE_URL}/api/admin/payments/export`,
  ADMIN_PAYMENTS_VERIFY: (id) => `${API_BASE_URL}/api/admin/payments/${id}/verify`,
  ADMIN_PAYMENT_DETAIL: (id) => `${API_BASE_URL}/api/admin/payments/${id}`,
  ADMIN_DASHBOARD: `${API_BASE_URL}/api/admin/dashboard`,
  NOTIFICATIONS: `${API_BASE_URL}/api/notifications`,
  NOTIFICATION_UNREAD_COUNT: `${API_BASE_URL}/api/notifications/unread-count`,
  NOTIFICATION_BY_ID: (id) => `${API_BASE_URL}/api/notifications/${encodeURIComponent(id)}`,
  NOTIFICATION_MARK_READ: (id) => `${API_BASE_URL}/api/notifications/${encodeURIComponent(id)}/read`,
  NOTIFICATION_MARK_ALL_READ: `${API_BASE_URL}/api/notifications/read-all`,
  NOTIFICATION_ARCHIVE: (id) => `${API_BASE_URL}/api/notifications/${encodeURIComponent(id)}/archive`,
  NOTIFICATION_HUB: `${API_BASE_URL}/hubs/notifications`,
};

