// API Configuration
// export const API_BASE_URL = 'https://localhost:7084'; 
export const API_BASE_URL = 'http://localhost:5274';

export const ENDPOINTS = {
  LOGIN: `${API_BASE_URL}/api/auth/login`,
  REGISTER: `${API_BASE_URL}/api/auth/register`,
  GOOGLE_LOGIN: `${API_BASE_URL}/api/auth/oauth/google`,
  FORGOT_PASSWORD: `${API_BASE_URL}/api/auth/forgot-password`,
  RESET_PASSWORD: `${API_BASE_URL}/api/auth/reset-password`,
  GET_PROFILE: `${API_BASE_URL}/api/users/me`,
  UPDATE_PROFILE: `${API_BASE_URL}/api/users/me/profile`,
  UPDATE_AVATAR: `${API_BASE_URL}/api/users/me/avatar`,
  CHANGE_PASSWORD: `${API_BASE_URL}/api/users/me/security`,
  CV_GET_MY: `${API_BASE_URL}/api/CVFile/MyCV`,
  CV_GET_HISTORY: `${API_BASE_URL}/api/CVFile/history`,
  CV_UPLOAD: `${API_BASE_URL}/api/CVFile/upload`,
  CV_DELETE: (id) => `${API_BASE_URL}/api/CVFile/${id}`,
  CV_PARSE: (id) => `${API_BASE_URL}/api/CVFile/${id}/parse`,
  CV_STATUS: (id) => `${API_BASE_URL}/api/CVFile/${id}/status`,
  CV_PARSED_DATA: (id) => `${API_BASE_URL}/api/CVFile/${id}/parsed-data`,
  CV_CONFIRM: (id) => `${API_BASE_URL}/api/CVFile/${id}/confirm`,
  JD_GET_HISTORY: `${API_BASE_URL}/api/JDFile/history`,
  JD_UPLOAD: `${API_BASE_URL}/api/JDFile/upload`,
  JD_SUBMIT_TEXT: `${API_BASE_URL}/api/JDFile/text`,
  JD_DELETE: (id) => `${API_BASE_URL}/api/JDFile/${id}`,
  JD_PARSE: (id) => `${API_BASE_URL}/api/JDFile/${id}/parse`,
  JD_STATUS: (id) => `${API_BASE_URL}/api/JDFile/${id}/status`,
  JD_PARSED_DATA: (id) => `${API_BASE_URL}/api/JDFile/${id}/parsed-data`,
  JD_CONFIRM: (id) => `${API_BASE_URL}/api/JDFile/${id}/confirm`,
  JD_MATCH_CV: (jdId, cvId) => `${API_BASE_URL}/api/JDFile/${jdId}/match-cv/${cvId}`,
  INTERVIEW_SESSIONS: `${API_BASE_URL}/api/InterviewSession`,
  INTERVIEW_SESSION: (id) => `${API_BASE_URL}/api/InterviewSession/${id}`,
  INTERVIEW_SESSION_START: (id) => `${API_BASE_URL}/api/InterviewSession/${id}/start`,
  INTERVIEW_CAMPAIGN: (campaignId) => `${API_BASE_URL}/api/InterviewSession/campaign/${campaignId}`,
  INTERVIEW_AVAILABLE_TYPES: (jdId) => `${API_BASE_URL}/api/InterviewSession/jd/${jdId}/available-types`,
  QUESTIONS_GET: `${API_BASE_URL}/api/questions`,
  QUESTIONS_GET_BY_ID: (id) => `${API_BASE_URL}/api/questions/${id}`,
  SAVED_QUESTIONS_GET: `${API_BASE_URL}/api/SavedQuestions`,
  SAVED_QUESTIONS_SAVE: (id) => `${API_BASE_URL}/api/SavedQuestions/${id}`,
  SAVED_QUESTIONS_UNSAVE: (id) => `${API_BASE_URL}/api/SavedQuestions/${id}`,
  ADMIN_USERS: `${API_BASE_URL}/api/admin/users`,
  ADMIN_USER_LOCK: (userId) => `${API_BASE_URL}/api/admin/users/${userId}/lock`,
  ADMIN_USER_UNLOCK: (userId) => `${API_BASE_URL}/api/admin/users/${userId}/unlock`,
  ADMIN_USER_ROLE: (userId) => `${API_BASE_URL}/api/admin/users/${userId}/role`,
  ADMIN_QUESTIONS: `${API_BASE_URL}/api/admin/questions`,
  ADMIN_QUESTIONS_FILTERS: `${API_BASE_URL}/api/admin/questions/filters`,
  ADMIN_QUESTIONS_BY_ID: (id) => `${API_BASE_URL}/api/admin/questions/${id}`,
  ADMIN_QUESTIONS_IMPORT: `${API_BASE_URL}/api/admin/questions/import`,
  AUDIO_SPEECH_TO_TEXT: `${API_BASE_URL}/api/Audio/speech-to-text`,
};
