export const TechnicalV2FlowPhase = Object.freeze({
  CHECKING_SESSION: 'checking-session',
  INITIALIZING: 'initializing',
  LOADING_QUESTION: 'loading-question',
  READY_TO_ANSWER: 'ready-to-answer',
  SUBMITTING_ANSWER: 'submitting-answer',
  EVALUATING_ANSWER: 'evaluating-answer',
  COMPLETING: 'completing',
  COMPLETED: 'completed',
  SESSION_CONFLICT: 'session-conflict',
  RECOVERABLE_ERROR: 'recoverable-error',
  FATAL_ERROR: 'fatal-error',
});

export const TechnicalV2ErrorCode = Object.freeze({
  SESSION_NOT_FOUND: 'SESSION_NOT_FOUND',
  SESSION_ACCESS_DENIED: 'SESSION_ACCESS_DENIED',
  WRONG_ROUND_TYPE: 'WRONG_ROUND_TYPE',
  RUNTIME_VERSION_REQUIRED: 'RUNTIME_VERSION_REQUIRED',
  CAMPAIGN_NOT_ACTIVE: 'CAMPAIGN_NOT_ACTIVE',
  SESSION_CANCELLED: 'SESSION_CANCELLED',
  SESSION_START_REJECTED: 'SESSION_START_REJECTED',
  NOT_INITIALIZED: 'NOT_INITIALIZED',
  ROUND_COMPLETED: 'ROUND_COMPLETED',
  ALL_QUESTIONS_ANSWERED: 'ALL_QUESTIONS_ANSWERED',
  QUESTION_NOT_FOUND: 'QUESTION_NOT_FOUND',
  IDEMPOTENCY_KEY_REQUIRED: 'IDEMPOTENCY_KEY_REQUIRED',
  IDEMPOTENCY_PAYLOAD_MISMATCH: 'IDEMPOTENCY_PAYLOAD_MISMATCH',
  ALREADY_ANSWERED: 'ALREADY_ANSWERED',
  EVALUATION_PROCESSING: 'EVALUATION_PROCESSING',
  QUESTIONS_NOT_FINALIZED: 'QUESTIONS_NOT_FINALIZED',
  RESULT_NOT_AVAILABLE: 'RESULT_NOT_AVAILABLE',
  FINAL_FEEDBACK_PROCESSING: 'FINAL_FEEDBACK_PROCESSING',
  TRANSCRIPT_REQUIRED: 'TRANSCRIPT_REQUIRED',
  NETWORK_ERROR: 'NETWORK_ERROR',
  REQUEST_TIMEOUT: 'REQUEST_TIMEOUT',
  UNKNOWN_ERROR: 'UNKNOWN_ERROR',
});

export const TechnicalV2SessionStatus = Object.freeze({
  ACTIVE: 'Active',
  COMPLETED: 'Completed',
  CANCELLED: 'Cancelled',
});
