namespace ai_speis_be.Models.Enums;

public enum NotificationRecipientRole
{
    USER,
    ADMIN
}

public enum NotificationCategory
{
    INTERVIEW,
    FEEDBACK,
    PROFILE,
    SUBSCRIPTION,
    AI_EVALUATION,
    SYSTEM
}

public enum NotificationSeverity
{
    INFO,
    SUCCESS,
    WARNING,
    ERROR,
    CRITICAL
}

public enum NotificationReadStatus
{
    UNREAD,
    READ,
    ARCHIVED
}

public enum NotificationActionStatus
{
    ACTIVE,
    COMPLETED,
    EXPIRED,
    CANCELLED
}

// The public notification contract. Do not add operational/transient states here.
public enum NotificationType
{
    INTERVIEW_SESSION_READY,
    INTERVIEW_SESSION_INTERRUPTED,
    INTERVIEW_SESSION_EXPIRED,
    INTERVIEW_ROUND_COMPLETED,
    ALL_INTERVIEW_ROUNDS_COMPLETED,
    INTERVIEW_FEEDBACK_READY,
    PROFILE_INFORMATION_REQUIRED,
    CV_PROCESSING_FAILED,
    JD_INFORMATION_REQUIRED,
    JD_PROCESSING_FAILED,
    SUBSCRIPTION_ACTIVATED,
    SUBSCRIPTION_EXPIRING_SOON,
    SUBSCRIPTION_EXPIRED,
    SUBSCRIPTION_PAYMENT_FAILED,
    SUBSCRIPTION_CANCELLED,
    SUBSCRIPTION_PLAN_CHANGED,
    SUBSCRIPTION_USAGE_LIMIT_REACHED,
    AI_EVALUATION_REQUIRES_REVIEW,
    AI_EVALUATION_FAILED,
    FINAL_FEEDBACK_FAILED,
    SYSTEM_SERVICE_UNAVAILABLE,
    SUBSCRIPTION_PAYMENT_REQUIRES_REVIEW,
    SUBSCRIPTION_ACTIVATION_FAILED,
    SUBSCRIPTION_DATA_INCONSISTENT,
    CV_UPLOADED,
    CV_PROCESSING_COMPLETED,
    JD_UPLOADED,
    JD_PROCESSING_COMPLETED,
    PROFILE_UPDATED,
    SUBSCRIPTION_PAYMENT_SUCCEEDED,
    WEEKLY_SYSTEM_STATISTICS
}

public enum NotificationEntityType
{
    INTERVIEW_SESSION,
    INTERVIEW_ROUND,
    INTERVIEW_RESULT,
    USER_PROFILE,
    CV,
    JOB_DESCRIPTION,
    SUBSCRIPTION,
    PAYMENT,
    AI_EVALUATION,
    SYSTEM_SERVICE
}
