const COPY = {
  vi: {
    modes: {
      All: 'Tất cả chế độ',
      Practice: 'Luyện tập',
      Mock: 'Phỏng vấn mô phỏng',
      RealTest: 'Phỏng vấn mô phỏng',
    },
    statuses: { 
      Pending: 'Chờ bắt đầu', 
      Active: 'Đang diễn ra', 
      Completed: 'Hoàn thành', 
      Cancelled: 'Đã hủy', 
      Expired: 'Đã hết hạn' 
    },
    rounds: { 
      Technical: 'Kỹ thuật', 
      Behavior: 'Hành vi', 
      Behavioral: 'Hành vi',
      Code: 'Lập trình',
      Coding: 'Lập trình',
      All: 'Tất cả các vòng'
    },
    history: {
      eyebrow: 'Luyện tập',
      title: 'Lịch sử phỏng vấn', 
      subtitle: 'Xem lại các buổi phỏng vấn cá nhân, kết quả từng vòng và theo dõi tiến bộ của bạn.',
      
      // Metrics
      total: 'Tổng số buổi phỏng vấn',
      practiceCount: 'Phiên Luyện tập',
      mockCount: 'Phiên Mock Interview',
      completed: 'Đã hoàn thành',
      active: 'Đang diễn ra',
      completionRate: 'Tỷ lệ hoàn thành',
      
      // Filter & Search
      search: 'Tìm phiên phỏng vấn (VD: Practice, Mock, Technical...)',
      status: 'Trạng thái', 
      round: 'Vòng phỏng vấn',
      mode: 'Chế độ',
      all: 'Tất cả', 
      reset: 'Đặt lại', 
      time: 'Thời gian', 
      campaign: 'Đợt phỏng vấn',
      answers: 'Câu trả lời', 
      language: 'Ngôn ngữ', 
      actions: 'Hành động', 
      
      // Card specific
      practiceSessionName: 'Practice Session #{{id}}',
      mockSessionName: 'Mock Interview #{{id}}',
      fallbackMockTitle: 'Phỏng vấn mô phỏng',
      fallbackPracticeTitle: 'Luyện tập',
      sessionIdLabel: 'Session #{{id}}',
      roundsCount: '{{count}} vòng phỏng vấn',
      roundsProgress: 'Tiến độ: {{completed}}/{{total}} vòng',
      overallScore: 'Điểm tổng thể',
      avgScore: 'Điểm trung bình',
      noScore: 'Chưa có kết quả',
      newInterviewBtn: 'Phỏng vấn mới',
      viewResultBtn: 'Xem kết quả',
      viewDetailBtn: 'Xem chi tiết',
      
      // States & Dialog
      loading: 'Đang tải lịch sử phỏng vấn…',
      loadTitle: 'Chưa thể tải lịch sử', 
      emptyTitle: 'Bạn chưa có buổi phỏng vấn nào', 
      emptyDescription: 'Hãy khởi tạo phiên phỏng vấn đầu tiên để hệ thống ghi nhận kết quả và đánh giá năng lực của bạn.',
      noResultsTitle: 'Không tìm thấy phiên phỏng vấn phù hợp', 
      noResultsDescription: 'Hãy thay đổi từ khóa hoặc xóa bộ lọc để tìm kiếm thêm phiên phỏng vấn khác.', 
      clearFilters: 'Xóa bộ lọc', 
      retry: 'Thử lại',
      viewDetail: 'Xem chi tiết', 
      review: 'Xem kết quả', 
      detailAria: 'Xem chi tiết đợt phỏng vấn {{id}}', 
      reviewAria: 'Xem kết quả vòng {{round}}',
      detailEyebrow: 'CHI TIẾT ĐỢT PHỎNG VẤN', 
      detailTitle: 'Đợt phỏng vấn #{{id}}', 
      close: 'Đóng', 
      closeAria: 'Đóng chi tiết', 
      started: 'Bắt đầu', 
      finished: 'Hoàn thành',
      duration: 'Thời lượng cấu hình', 
      minutes: '{{count}} phút', 
      totalScore: 'Điểm tổng', 
      sessionRounds: 'Các vòng phỏng vấn trong buổi này', 
      loadingResult: 'Đang tải kết quả…', 
      scoreError: 'Không thể tải điểm tổng quan của đợt phỏng vấn này.', 
      answerCount: '{{completed}}/{{total}} câu trả lời',
      unauthorized: 'Bạn không có quyền xem lịch sử phỏng vấn.', 
      loadError: 'Không thể tải lịch sử phỏng vấn. Vui lòng thử lại.',
      showing: 'Hiển thị', 
      of: 'trên tổng số', 
      sessionsUnit: 'buổi phỏng vấn', 
      pageSize: 'Số lượng mỗi trang:',
      firstPage: 'Trang đầu', 
      lastPage: 'Trang cuối', 
      previousPage: 'Trang trước', 
      nextPage: 'Trang tiếp',
    },
    review: {
      technical: 'Kỹ thuật', 
      behavioral: 'Hành vi', 
      fallbackRound: 'Phỏng vấn', 
      title: 'Review câu trả lời', 
      eyebrow: 'REVIEW TỪNG CÂU TRẢ LỜI', 
      back: 'Lịch sử phỏng vấn',
      loading: 'Đang tải câu trả lời và đánh giá…', 
      loadTitle: 'Chưa thể mở review', 
      retry: 'Thử lại', 
      backHistory: 'Về lịch sử',
      missingId: 'Không tìm thấy mã phiên phỏng vấn.', 
      forbidden: 'Bạn không có quyền xem phiên phỏng vấn này.', 
      notFound: 'Không tìm thấy phiên phỏng vấn hoặc kết quả review.', 
      timeout: 'Yêu cầu mất quá nhiều thời gian. Vui lòng thử lại.', 
      unsupported: 'Vòng phỏng vấn này chưa hỗ trợ review từng câu trả lời.', 
      loadError: 'Không thể tải review câu trả lời. Vui lòng thử lại.',
      emptyTitle: 'Chưa có câu trả lời để review', 
      emptyDescription: 'Phiên này chưa có dữ liệu câu trả lời hoặc transcript phù hợp để hiển thị.', 
      questionList: 'Danh sách câu hỏi', 
      waitingEvaluation: 'Đang chờ đánh giá',
      mainQuestion: 'CÂU HỎI CHÍNH', 
      question: 'CÂU HỎI', 
      missingQuestion: 'Câu hỏi không có nội dung', 
      skill: 'Kỹ năng: {{skill}}', 
      transcript: 'Transcript câu trả lời', 
      missingTranscript: 'Không có transcript cho câu trả lời này.', 
      aiFeedback: 'Nhận xét AI', 
      rubric: 'Tiêu chí đánh giá', 
      strengths: 'Điểm mạnh', 
      improvements: 'Điểm cần cải thiện', 
      practiceTips: 'Gợi ý luyện tập', 
      followUps: 'Câu hỏi làm rõ / theo dõi', 
      missingFollowUpTranscript: 'Không có transcript.', 
      previous: 'Câu trước', 
      next: 'Câu tiếp',
    },
  },
  en: {
    modes: {
      All: 'All Modes',
      Practice: 'Practice',
      Mock: 'Mock Interview',
      RealTest: 'Mock Interview',
    },
    statuses: { 
      Pending: 'Pending', 
      Active: 'In progress', 
      Completed: 'Completed', 
      Cancelled: 'Cancelled', 
      Expired: 'Expired' 
    },
    rounds: { 
      Technical: 'Technical', 
      Behavior: 'Behavioral', 
      Behavioral: 'Behavioral',
      Code: 'Coding',
      Coding: 'Coding',
      All: 'All Rounds'
    },
    history: {
      eyebrow: 'Practice',
      title: 'Interview History', 
      subtitle: 'Review your personal interview sessions, track round progress, and analyze results.',
      
      // Metrics
      total: 'Total Interview Sessions',
      practiceCount: 'Practice Sessions',
      mockCount: 'Mock Interviews',
      completed: 'Completed Sessions',
      active: 'In Progress',
      completionRate: 'Completion Rate',
      
      // Filter & Search
      search: 'Search interview sessions (e.g. Practice, Mock, Technical...)',
      status: 'Status', 
      round: 'Interview Round',
      mode: 'Mode',
      all: 'All', 
      reset: 'Reset', 
      time: 'Time', 
      campaign: 'Interview Campaign',
      answers: 'Answers', 
      language: 'Language', 
      actions: 'Actions', 
      
      // Card specific
      practiceSessionName: 'Practice Session #{{id}}',
      mockSessionName: 'Mock Interview #{{id}}',
      fallbackMockTitle: 'Mock Interview',
      fallbackPracticeTitle: 'Interview Practice',
      sessionIdLabel: 'Session #{{id}}',
      roundsCount: '{{count}} interview rounds',
      roundsProgress: 'Progress: {{completed}}/{{total}} rounds',
      overallScore: 'Overall Score',
      avgScore: 'Average Score',
      noScore: 'No score yet',
      newInterviewBtn: 'New Interview',
      viewResultBtn: 'View Results',
      viewDetailBtn: 'View Details',

      // States & Dialog
      loading: 'Loading interview history…',
      loadTitle: 'Unable to load history', 
      emptyTitle: 'No interview sessions yet', 
      emptyDescription: 'Start your first interview session to track your progress and evaluate your skills.',
      noResultsTitle: 'No matching interview sessions', 
      noResultsDescription: 'Try changing your search terms or clearing filters to find more sessions.', 
      clearFilters: 'Clear filters', 
      retry: 'Retry',
      viewDetail: 'View details', 
      review: 'View Results', 
      detailAria: 'View details for interview campaign {{id}}', 
      reviewAria: 'Review results for {{round}} round',
      detailEyebrow: 'INTERVIEW CAMPAIGN DETAILS', 
      detailTitle: 'Interview Campaign #{{id}}', 
      close: 'Close', 
      closeAria: 'Close details', 
      started: 'Started', 
      finished: 'Completed',
      duration: 'Configured duration', 
      minutes: '{{count}} minutes', 
      totalScore: 'Overall score', 
      sessionRounds: 'Rounds in this session', 
      loadingResult: 'Loading result…', 
      scoreError: 'Unable to load overall score for this campaign.', 
      answerCount: '{{completed}}/{{total}} answers',
      unauthorized: 'You do not have permission to view interview history.', 
      loadError: 'Unable to load interview history. Please try again.',
      showing: 'Showing', 
      of: 'of', 
      sessionsUnit: 'interview sessions', 
      pageSize: 'Items per page:',
      firstPage: 'First page', 
      lastPage: 'Last page', 
      previousPage: 'Previous page', 
      nextPage: 'Next page',
    },
    review: {
      technical: 'Technical', 
      behavioral: 'Behavioral', 
      fallbackRound: 'Interview', 
      title: 'Answer Review', 
      eyebrow: 'REVIEW EACH ANSWER', 
      back: 'Interview history',
      loading: 'Loading answers and evaluation…', 
      loadTitle: 'Unable to open review', 
      retry: 'Retry', 
      backHistory: 'Back to history',
      missingId: 'Interview session ID missing.', 
      forbidden: 'You do not have permission to view this interview session.', 
      notFound: 'Interview session or review result not found.', 
      timeout: 'Request timed out. Please try again.', 
      unsupported: 'Answer review is not supported for this round.', 
      loadError: 'Unable to load answer review. Please try again.',
      emptyTitle: 'No answers to review', 
      emptyDescription: 'This session does not have answer data or a matching transcript to display.', 
      questionList: 'Question list', 
      waitingEvaluation: 'Awaiting evaluation',
      mainQuestion: 'MAIN QUESTION', 
      question: 'QUESTION', 
      missingQuestion: 'Question content is unavailable', 
      skill: 'Skill: {{skill}}', 
      transcript: 'Answer transcript', 
      aiFeedback: 'AI feedback', 
      rubric: 'Evaluation criteria', 
      strengths: 'Strengths', 
      improvements: 'Areas to improve', 
      practiceTips: 'Practice suggestions', 
      followUps: 'Clarifying / follow-up questions', 
      missingFollowUpTranscript: 'No transcript is available.', 
      previous: 'Previous', 
      next: 'Next',
    },
  },
};

export const getInterviewHistoryCopy = (language) => (
  String(language || '').toLowerCase().startsWith('en') ? COPY.en : COPY.vi
);

export const formatInterviewTitle = (campaign, copy) => {
  if (!campaign) return copy?.history?.fallbackPracticeTitle || 'Interview Practice';

  const rawJobTitle = campaign.jobTitle || campaign.JobTitle || campaign.roleTarget || campaign.positionTitle || campaign.jdTitle;
  const isMock = (campaign.mode || '').toLowerCase().includes('mock') || (campaign.sessions?.length === 3);
  const modeLabel = isMock ? copy.modes.Mock : copy.modes.Practice;

  if (rawJobTitle && typeof rawJobTitle === 'string' && rawJobTitle.trim().length > 0) {
    const cleanJobTitle = rawJobTitle.trim();
    return `${cleanJobTitle} — ${modeLabel}`;
  }

  return isMock ? copy.history.fallbackMockTitle : copy.history.fallbackPracticeTitle;
};
