// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ai_speis_be.Models;

#nullable disable

namespace ai_speis_be.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260719121042_AddTechnicalInterviewModule")]
    partial class AddTechnicalInterviewModule
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.18")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ai_speis_be.Models.AIInteractionLog", b =>
                {
                    b.Property<Guid>("AIInteractionLogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("AttemptId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ErrorCode")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal?>("EstimatedCost")
                        .HasColumnType("decimal(18,8)");

                    b.Property<bool>("FallbackUsed")
                        .HasColumnType("bit");

                    b.Property<int?>("InputTokenCount")
                        .HasColumnType("int");

                    b.Property<int>("InterviewSessionId")
                        .HasColumnType("int");

                    b.Property<long>("LatencyMs")
                        .HasColumnType("bigint");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<int>("OperationType")
                        .HasColumnType("int");

                    b.Property<int?>("OutputTokenCount")
                        .HasColumnType("int");

                    b.Property<string>("PromptVersion")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("RubricVersion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("AIInteractionLogId");

                    b.HasIndex("AttemptId");

                    b.HasIndex("InterviewSessionId", "CreatedAt");

                    b.ToTable("AIInteractionLog");
                });

            modelBuilder.Entity("ai_speis_be.Models.CVExtractedProfile", b =>
                {
                    b.Property<int>("ExtractedProfileId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ExtractedProfileId"));

                    b.Property<int>("CVFileId")
                        .HasColumnType("int");

                    b.Property<decimal?>("ConfidenceScore")
                        .HasColumnType("decimal(5,2)");

                    b.Property<DateTime?>("ConfirmedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ConfirmedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Education")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Experience")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("OverallAssessment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RawAiOutput")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleTarget")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Strengths")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Weaknesses")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ExtractedProfileId");

                    b.HasIndex("ConfirmedBy");

                    b.HasIndex(new[] { "CVFileId" }, "IX_CVExtractedProfile_CVFileId")
                        .IsUnique();

                    b.ToTable("CVExtractedProfile");
                });

            modelBuilder.Entity("ai_speis_be.Models.CVFile", b =>
                {
                    b.Property<int>("CVFileId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CVFileId"));

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("FileSize")
                        .HasColumnType("bigint");

                    b.Property<string>("FileType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("CVFileId");

                    b.HasIndex(new[] { "CVFileId" }, "IX_CVFile_CVFileId")
                        .IsUnique();

                    b.HasIndex(new[] { "UserId" }, "IX_CVFile_UserId");

                    b.ToTable("CVFile");
                });

            modelBuilder.Entity("ai_speis_be.Models.CVProject", b =>
                {
                    b.Property<int>("CVProjectId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CVProjectId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Duration")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("ExtractedProfileId")
                        .HasColumnType("int");

                    b.Property<string>("ProjectName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("ProjectSummary")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TechnologyStack")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CVProjectId");

                    b.HasIndex(new[] { "ExtractedProfileId" }, "IX_CVProject_ExtractedProfileId");

                    b.ToTable("CVProject");
                });

            modelBuilder.Entity("ai_speis_be.Models.CVSkill", b =>
                {
                    b.Property<int>("CVSkillId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CVSkillId"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("ExtractedProfileId")
                        .HasColumnType("int");

                    b.Property<string>("SkillName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("CVSkillId");

                    b.HasIndex("ExtractedProfileId", "SkillName")
                        .IsUnique();

                    b.HasIndex(new[] { "ExtractedProfileId" }, "IX_CVSkill_ExtractedProfileId");

                    b.ToTable("CVSkill");
                });

            modelBuilder.Entity("ai_speis_be.Models.CodingQuestion", b =>
                {
                    b.Property<int>("CodingQuestionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CodingQuestionId"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("InterviewSessionId")
                        .HasColumnType("int");

                    b.Property<int>("MemoryLimit")
                        .HasColumnType("int");

                    b.Property<double>("TimeLimit")
                        .HasColumnType("float");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("CodingQuestionId");

                    b.HasIndex("InterviewSessionId");

                    b.ToTable("CodingQuestion");
                });

            modelBuilder.Entity("ai_speis_be.Models.CodingQuestionTemplate", b =>
                {
                    b.Property<int>("TemplateId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TemplateId"));

                    b.Property<int>("CodingQuestionId")
                        .HasColumnType("int");

                    b.Property<int>("LanguageId")
                        .HasColumnType("int");

                    b.Property<string>("TemplateCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TemplateId");

                    b.HasIndex("CodingQuestionId");

                    b.ToTable("CodingQuestionTemplate");
                });

            modelBuilder.Entity("ai_speis_be.Models.CodingSubmission", b =>
                {
                    b.Property<int>("CodingSubmissionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CodingSubmissionId"));

                    b.Property<int>("CodingQuestionId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("InterviewSessionId")
                        .HasColumnType("int");

                    b.Property<int>("LanguageId")
                        .HasColumnType("int");

                    b.Property<int>("MaxMemoryKb")
                        .HasColumnType("int");

                    b.Property<double>("MaxTimeMs")
                        .HasColumnType("float");

                    b.Property<int>("PassedTestCases")
                        .HasColumnType("int");

                    b.Property<string>("SourceCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("TotalTestCases")
                        .HasColumnType("int");

                    b.HasKey("CodingSubmissionId");

                    b.HasIndex("CodingQuestionId");

                    b.HasIndex("InterviewSessionId");

                    b.ToTable("CodingSubmission");
                });

            modelBuilder.Entity("ai_speis_be.Models.InterviewCampaign", b =>
                {
                    b.Property<int>("InterviewCampaignId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("InterviewCampaignId"));

                    b.Property<int>("CVExtractedProfileId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CancelledAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("DurationMinutes")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("JDExtractedProfileId")
                        .HasColumnType("int");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int>("Mode")
                        .HasColumnType("int");

                    b.Property<bool>("QuotaRefunded")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("InterviewCampaignId");

                    b.HasIndex("CVExtractedProfileId");

                    b.HasIndex("JDExtractedProfileId");

                    b.HasIndex("UserId", "Status")
                        .HasDatabaseName("IX_InterviewCampaign_UserId_Status");

                    b.ToTable("InterviewCampaign", t =>
                        {
                            t.HasCheckConstraint("CK_InterviewCampaign_DurationMinutes", "[DurationMinutes] IN (10, 15, 20)");
                        });
                });

            modelBuilder.Entity("ai_speis_be.Models.InterviewSession", b =>
                {
                    b.Property<int>("InterviewSessionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("InterviewSessionId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Difficulty")
                        .HasColumnType("int");

                    b.Property<int>("InterviewCampaignId")
                        .HasColumnType("int");

                    b.Property<int>("InterviewRoundType")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("QuestionCount")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("TechnicalAiModel")
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("TechnicalAiProvider")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("TechnicalCompletedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("TechnicalCompletedMainQuestionCount")
                        .HasColumnType("int");

                    b.Property<int>("TechnicalConcurrencyVersion")
                        .IsConcurrencyToken()
                        .HasColumnType("int");

                    b.Property<string>("TechnicalExperienceLevel")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal?>("TechnicalFinalScore")
                        .HasColumnType("decimal(5,2)");

                    b.Property<string>("TechnicalJobRole")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("TechnicalLanguage")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("TechnicalPerformanceBand")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TechnicalRubricVersion")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TechnicalScoringPolicyVersion")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TechnicalSelectedSkillsJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("TechnicalStartedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("TechnicalState")
                        .HasColumnType("int");

                    b.Property<string>("TechnicalSummaryJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("InterviewSessionId");

                    b.HasIndex("InterviewCampaignId");

                    b.ToTable("InterviewSession");
                });

            modelBuilder.Entity("ai_speis_be.Models.JDExtractedProfile", b =>
                {
                    b.Property<int>("ExtractedProfileId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ExtractedProfileId"));

                    b.Property<string>("CompanyCharacteristics")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("ConfidenceScore")
                        .HasColumnType("decimal(5,2)");

                    b.Property<DateTime?>("ConfirmedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ConfirmedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ExperienceLevel")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsConfirmed")
                        .HasColumnType("bit");

                    b.Property<int>("JDFileId")
                        .HasColumnType("int");

                    b.Property<string>("JobTitle")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("NiceToHaveSkills")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RawAiOutput")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RequiredSkills")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Responsibilities")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleTarget")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("ExtractedProfileId");

                    b.HasIndex("ConfirmedBy");

                    b.HasIndex(new[] { "JDFileId" }, "IX_JDExtractedProfile_JDFileId")
                        .IsUnique();

                    b.ToTable("JDExtractedProfile");
                });

            modelBuilder.Entity("ai_speis_be.Models.JDFile", b =>
                {
                    b.Property<int>("JDFileId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("JDFileId"));

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("FileName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FilePath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("FileSize")
                        .HasColumnType("bigint");

                    b.Property<string>("FileType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("InputType")
                        .HasColumnType("int");

                    b.Property<string>("RawText")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("JDFileId");

                    b.HasIndex(new[] { "JDFileId" }, "IX_JDFile_JDFileId")
                        .IsUnique();

                    b.HasIndex(new[] { "UserId" }, "IX_JDFile_UserId");

                    b.ToTable("JDFile");
                });

            modelBuilder.Entity("ai_speis_be.Models.Payment", b =>
                {
                    b.Property<int>("PaymentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PaymentId"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("OrderCode")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<int>("PackageId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("PaidAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("PaymentId");

                    b.HasIndex(new[] { "OrderCode" }, "IX_Payment_OrderCode")
                        .IsUnique();

                    b.HasIndex(new[] { "Status" }, "IX_Payment_Status");

                    b.HasIndex(new[] { "UserId" }, "IX_Payment_UserId");

                    b.ToTable("Payment");
                });

            modelBuilder.Entity("ai_speis_be.Models.Question", b =>
                {
                    b.Property<int>("QuestionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("QuestionId"));

                    b.Property<string>("ClarificationQuestion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CompanyCategory")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CompanySubcategory")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DeletedBy")
                        .HasColumnType("int");

                    b.Property<int>("Difficulty")
                        .HasColumnType("int");

                    b.Property<string>("EmbeddingText")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ExpectedKeyPoints")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ExperienceLevel")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FollowUp1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FollowUp2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("KeywordTags")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Language")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LevelTags")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Major")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("QdrantPayloadJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("QuestionContent")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("QuestionType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleTarget")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ScoringRubric")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Skill")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SuggestedAnswer")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TimeLimitSeconds")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("QuestionId");

                    b.HasIndex(new[] { "QuestionId" }, "IX_Question_QuestionId")
                        .IsUnique();

                    b.HasIndex(new[] { "UserId" }, "IX_Question_UserId");

                    b.ToTable("Question");
                });

            modelBuilder.Entity("ai_speis_be.Models.Role", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RoleId"));

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.HasKey("RoleId");

                    b.HasIndex(new[] { "RoleId" }, "IX_Role_RoleId")
                        .IsUnique();

                    b.HasIndex(new[] { "Status" }, "IX_Role_Status");

                    b.ToTable("Role");

                    b.HasData(
                        new
                        {
                            RoleId = 1,
                            Description = "Quản trị viên",
                            RoleName = "admin",
                            Status = true
                        },
                        new
                        {
                            RoleId = 2,
                            Description = "Người dùng",
                            RoleName = "user",
                            Status = true
                        });
                });

            modelBuilder.Entity("ai_speis_be.Models.SavedQuestion", b =>
                {
                    b.Property<int>("SavedQuestionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SavedQuestionId"));

                    b.Property<int>("QuestionId")
                        .HasColumnType("int");

                    b.Property<DateTime>("SavedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("SavedQuestionId");

                    b.HasIndex("QuestionId");

                    b.HasIndex("UserId", "QuestionId")
                        .IsUnique();

                    b.ToTable("SavedQuestion");
                });

            modelBuilder.Entity("ai_speis_be.Models.SubmissionTestCaseResult", b =>
                {
                    b.Property<int>("ResultId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ResultId"));

                    b.Property<string>("ActualOutput")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CodingSubmissionId")
                        .HasColumnType("int");

                    b.Property<string>("CompileOutput")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MemoryKb")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Stderr")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TestCaseId")
                        .HasColumnType("int");

                    b.Property<double>("TimeMs")
                        .HasColumnType("float");

                    b.HasKey("ResultId");

                    b.HasIndex("CodingSubmissionId");

                    b.HasIndex("TestCaseId");

                    b.ToTable("SubmissionTestCaseResult");
                });

            modelBuilder.Entity("ai_speis_be.Models.TechnicalAnswerEvaluation", b =>
                {
                    b.Property<Guid>("EvaluationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("AiSuggestedOverallScore")
                        .HasColumnType("decimal(5,2)");

                    b.Property<Guid>("AttemptId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Confidence")
                        .HasColumnType("decimal(5,4)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Decision")
                        .HasColumnType("int");

                    b.Property<string>("DimensionEvaluationsJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("FinalOverallScore")
                        .HasColumnType("decimal(5,2)");

                    b.Property<string>("ImprovementSuggestionsJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IncorrectClaimsJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsFinalForMainQuestion")
                        .HasColumnType("bit");

                    b.Property<string>("MissingPointsJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ModelName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("PromptVersion")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<Guid>("RootMainAttemptId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("RubricVersion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ScoringBreakdownJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StrengthsJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("EvaluationId");

                    b.HasIndex("AttemptId")
                        .IsUnique();

                    b.HasIndex("RootMainAttemptId")
                        .IsUnique()
                        .HasFilter("[IsFinalForMainQuestion] = 1");

                    b.ToTable("TechnicalAnswerEvaluation");
                });

            modelBuilder.Entity("ai_speis_be.Models.TechnicalQuestionAttempt", b =>
                {
                    b.Property<Guid>("AttemptId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AnswerTranscript")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("AnsweredAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("AudioId")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DifficultySnapshot")
                        .HasColumnType("int");

                    b.Property<int>("InterviewSessionId")
                        .HasColumnType("int");

                    b.Property<int>("MainQuestionIndex")
                        .HasColumnType("int");

                    b.Property<Guid?>("ParentAttemptId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("QuestionContentSnapshot")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("QuestionId")
                        .HasColumnType("int");

                    b.Property<int>("QuestionType")
                        .HasColumnType("int");

                    b.Property<Guid>("RootMainAttemptId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("SequenceNumber")
                        .HasColumnType("int");

                    b.Property<string>("SkillSnapshot")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("SubmissionIdempotencyKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("SubskillSnapshot")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("AttemptId");

                    b.HasIndex("ParentAttemptId");

                    b.HasIndex("QuestionId");

                    b.HasIndex("InterviewSessionId", "SequenceNumber")
                        .IsUnique();

                    b.HasIndex("InterviewSessionId", "Status")
                        .IsUnique()
                        .HasFilter("[Status] = 0");

                    b.HasIndex("InterviewSessionId", "SubmissionIdempotencyKey")
                        .IsUnique()
                        .HasFilter("[SubmissionIdempotencyKey] IS NOT NULL");

                    b.ToTable("TechnicalQuestionAttempt");
                });

            modelBuilder.Entity("ai_speis_be.Models.TestCase", b =>
                {
                    b.Property<int>("TestCaseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TestCaseId"));

                    b.Property<int>("CodingQuestionId")
                        .HasColumnType("int");

                    b.Property<string>("ExpectedOutput")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Input")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsHidden")
                        .HasColumnType("bit");

                    b.Property<bool>("IsSample")
                        .HasColumnType("bit");

                    b.HasKey("TestCaseId");

                    b.HasIndex("CodingQuestionId");

                    b.ToTable("TestCase");
                });

            modelBuilder.Entity("ai_speis_be.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("EmailConfirmationToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("EmailConfirmationTokenExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("EmailConfirmedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("IsLocked")
                        .HasColumnType("bit");

                    b.Property<string>("LockReason")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("LockedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("LockedByUserId")
                        .HasColumnType("int");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordResetToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("PasswordResetTokenExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RemainingInterviewQuota")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("UserId");

                    b.HasIndex("RoleId");

                    b.HasIndex(new[] { "Email" }, "IX_User_Email");

                    b.HasIndex(new[] { "UserId" }, "IX_User_UserId")
                        .IsUnique();

                    b.ToTable("User", t =>
                        {
                            t.HasCheckConstraint("CK_User_RemainingInterviewQuota", "[RemainingInterviewQuota] >= 0");
                        });
                });

            modelBuilder.Entity("ai_speis_be.Models.UserProfile", b =>
                {
                    b.Property<int>("ProfileId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProfileId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Gender")
                        .HasColumnType("int");

                    b.Property<decimal>("Gpa")
                        .HasColumnType("decimal(3,2)");

                    b.Property<string>("Major")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("School")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("TargetPosition")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("ProfileId");

                    b.HasIndex(new[] { "ProfileId" }, "IX_UserProfile_ProfileId")
                        .IsUnique();

                    b.HasIndex(new[] { "UserId" }, "IX_UserProfile_UserId")
                        .IsUnique();

                    b.ToTable("UserProfile");
                });

            modelBuilder.Entity("ai_speis_be.Models.AIInteractionLog", b =>
                {
                    b.HasOne("ai_speis_be.Models.TechnicalQuestionAttempt", "Attempt")
                        .WithMany()
                        .HasForeignKey("AttemptId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("ai_speis_be.Models.InterviewSession", "InterviewSession")
                        .WithMany("AIInteractionLogs")
                        .HasForeignKey("InterviewSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Attempt");

                    b.Navigation("InterviewSession");
                });

            modelBuilder.Entity("ai_speis_be.Models.CVExtractedProfile", b =>
                {
                    b.HasOne("ai_speis_be.Models.CVFile", "CVFile")
                        .WithOne()
                        .HasForeignKey("ai_speis_be.Models.CVExtractedProfile", "CVFileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ai_speis_be.Models.User", "ConfirmedByUser")
                        .WithMany()
                        .HasForeignKey("ConfirmedBy")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("CVFile");

                    b.Navigation("ConfirmedByUser");
                });

            modelBuilder.Entity("ai_speis_be.Models.CVFile", b =>
                {
                    b.HasOne("ai_speis_be.Models.User", "User")
                        .WithMany("CVFiles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("ai_speis_be.Models.CVProject", b =>
                {
                    b.HasOne("ai_speis_be.Models.CVExtractedProfile", "ExtractedProfile")
                        .WithMany("Projects")
                        .HasForeignKey("ExtractedProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ExtractedProfile");
                });

            modelBuilder.Entity("ai_speis_be.Models.CVSkill", b =>
                {
                    b.HasOne("ai_speis_be.Models.CVExtractedProfile", "ExtractedProfile")
                        .WithMany("Skills")
                        .HasForeignKey("ExtractedProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ExtractedProfile");
                });

            modelBuilder.Entity("ai_speis_be.Models.CodingQuestion", b =>
                {
                    b.HasOne("ai_speis_be.Models.InterviewSession", "InterviewSession")
                        .WithMany()
                        .HasForeignKey("InterviewSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("InterviewSession");
                });

            modelBuilder.Entity("ai_speis_be.Models.CodingQuestionTemplate", b =>
                {
                    b.HasOne("ai_speis_be.Models.CodingQuestion", "CodingQuestion")
                        .WithMany("CodingQuestionTemplates")
                        .HasForeignKey("CodingQuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CodingQuestion");
                });

            modelBuilder.Entity("ai_speis_be.Models.CodingSubmission", b =>
                {
                    b.HasOne("ai_speis_be.Models.CodingQuestion", "CodingQuestion")
                        .WithMany("CodingSubmissions")
                        .HasForeignKey("CodingQuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ai_speis_be.Models.InterviewSession", "InterviewSession")
                        .WithMany()
                        .HasForeignKey("InterviewSessionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CodingQuestion");

                    b.Navigation("InterviewSession");
                });

            modelBuilder.Entity("ai_speis_be.Models.InterviewCampaign", b =>
                {
                    b.HasOne("ai_speis_be.Models.CVExtractedProfile", "CVExtractedProfile")
                        .WithMany()
                        .HasForeignKey("CVExtractedProfileId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ai_speis_be.Models.JDExtractedProfile", "JDExtractedProfile")
                        .WithMany()
                        .HasForeignKey("JDExtractedProfileId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ai_speis_be.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CVExtractedProfile");

                    b.Navigation("JDExtractedProfile");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ai_speis_be.Models.InterviewSession", b =>
                {
                    b.HasOne("ai_speis_be.Models.InterviewCampaign", "InterviewCampaign")
                        .WithMany("InterviewSessions")
                        .HasForeignKey("InterviewCampaignId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("InterviewCampaign");
                });

            modelBuilder.Entity("ai_speis_be.Models.JDExtractedProfile", b =>
                {
                    b.HasOne("ai_speis_be.Models.User", "ConfirmedByUser")
                        .WithMany()
                        .HasForeignKey("ConfirmedBy");

                    b.HasOne("ai_speis_be.Models.JDFile", "JDFile")
                        .WithMany()
                        .HasForeignKey("JDFileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ConfirmedByUser");

                    b.Navigation("JDFile");
                });

            modelBuilder.Entity("ai_speis_be.Models.JDFile", b =>
                {
                    b.HasOne("ai_speis_be.Models.User", "User")
                        .WithMany("JDFiles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("ai_speis_be.Models.Payment", b =>
                {
                    b.HasOne("ai_speis_be.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("ai_speis_be.Models.Question", b =>
                {
                    b.HasOne("ai_speis_be.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("ai_speis_be.Models.SavedQuestion", b =>
                {
                    b.HasOne("ai_speis_be.Models.Question", "Question")
                        .WithMany()
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ai_speis_be.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Question");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ai_speis_be.Models.SubmissionTestCaseResult", b =>
                {
                    b.HasOne("ai_speis_be.Models.CodingSubmission", "CodingSubmission")
                        .WithMany("SubmissionTestCaseResults")
                        .HasForeignKey("CodingSubmissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ai_speis_be.Models.TestCase", "TestCase")
                        .WithMany("SubmissionTestCaseResults")
                        .HasForeignKey("TestCaseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CodingSubmission");

                    b.Navigation("TestCase");
                });

            modelBuilder.Entity("ai_speis_be.Models.TechnicalAnswerEvaluation", b =>
                {
                    b.HasOne("ai_speis_be.Models.TechnicalQuestionAttempt", "Attempt")
                        .WithMany("Evaluations")
                        .HasForeignKey("AttemptId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Attempt");
                });

            modelBuilder.Entity("ai_speis_be.Models.TechnicalQuestionAttempt", b =>
                {
                    b.HasOne("ai_speis_be.Models.InterviewSession", "InterviewSession")
                        .WithMany("TechnicalQuestionAttempts")
                        .HasForeignKey("InterviewSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ai_speis_be.Models.TechnicalQuestionAttempt", "ParentAttempt")
                        .WithMany("ChildAttempts")
                        .HasForeignKey("ParentAttemptId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ai_speis_be.Models.Question", "Question")
                        .WithMany()
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("InterviewSession");

                    b.Navigation("ParentAttempt");

                    b.Navigation("Question");
                });

            modelBuilder.Entity("ai_speis_be.Models.TestCase", b =>
                {
                    b.HasOne("ai_speis_be.Models.CodingQuestion", "CodingQuestion")
                        .WithMany("TestCases")
                        .HasForeignKey("CodingQuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CodingQuestion");
                });

            modelBuilder.Entity("ai_speis_be.Models.User", b =>
                {
                    b.HasOne("ai_speis_be.Models.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("ai_speis_be.Models.UserProfile", b =>
                {
                    b.HasOne("ai_speis_be.Models.User", "User")
                        .WithOne()
                        .HasForeignKey("ai_speis_be.Models.UserProfile", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("ai_speis_be.Models.CVExtractedProfile", b =>
                {
                    b.Navigation("Projects");

                    b.Navigation("Skills");
                });

            modelBuilder.Entity("ai_speis_be.Models.CodingQuestion", b =>
                {
                    b.Navigation("CodingQuestionTemplates");

                    b.Navigation("CodingSubmissions");

                    b.Navigation("TestCases");
                });

            modelBuilder.Entity("ai_speis_be.Models.CodingSubmission", b =>
                {
                    b.Navigation("SubmissionTestCaseResults");
                });

            modelBuilder.Entity("ai_speis_be.Models.InterviewCampaign", b =>
                {
                    b.Navigation("InterviewSessions");
                });

            modelBuilder.Entity("ai_speis_be.Models.InterviewSession", b =>
                {
                    b.Navigation("AIInteractionLogs");

                    b.Navigation("TechnicalQuestionAttempts");
                });

            modelBuilder.Entity("ai_speis_be.Models.TechnicalQuestionAttempt", b =>
                {
                    b.Navigation("ChildAttempts");

                    b.Navigation("Evaluations");
                });

            modelBuilder.Entity("ai_speis_be.Models.TestCase", b =>
                {
                    b.Navigation("SubmissionTestCaseResults");
                });

            modelBuilder.Entity("ai_speis_be.Models.User", b =>
                {
                    b.Navigation("CVFiles");

                    b.Navigation("JDFiles");
                });
#pragma warning restore 612, 618
        }
    }
}
